### ISSUE TITLE
Windows build issues

### ISSUE THREAD

**Issue by dcodeIO** [devsnek/node-wasi#16]
Currently giving node-wasi a try for some AssemblyScript related testing. Unfortunately, on Win10, VC2017, node-gyp@5.0.2 I'm running into

```
c:\program files (x86)\windows kits\10\include\10.0.17763.0\um\winnt.h(154): fatal error C1189: #error:  "No Target Architecture" (Quelldatei wird kompiliert ..\src\binding.cc) [XY\node-wasi\build\wasi.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
```

Have tried upgrading to 12.6.0 and letting it install the Windows build tools as suggested by the installer, unfortunately without success.

Is this something well-known to mankind, like with a specific version of the tools or node?

**Edit:** Interestingly, the build appears to pick up the node-gyp version within nodejs/node_modules/npm/node_modules, which is older

```
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v3.8.0
```

**Edit:** This can be solved with a `npm install npm@latest -g` (apparently), but the error remains the same, just with

```
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v5.0.2
```

**Edit:** Same for v13.0.0-nightly201907156c430b48b9.

**Comment by devsnek** [comment]
hey dcode!

Unfortunately this has never been tested on windows, so you're in uncharted territory. If the issue is with node-gyp itself, perhaps @refack knows, but generally this is outside my area of knowledge.

**Comment by dcodeIO** [comment]
Thanks, will continue to investigate then :)
