### ISSUE TITLE
Pass arguments in _start function

### ISSUE THREAD

**Issue by Gregoirevda** [devsnek/node-wasi#2]
I'm trying to run the [wasmtime tutorial](https://github.com/CraneStation/wasmtime/blob/master/docs/WASI-tutorial.md#compiling-to-wasi) but I'm getting the first error in the C code `usage: %s <from> <to>\n", argv[0]`.

How can I pass arguments to the `_start` function?

**Comment by devsnek** [comment]
you can pass an `env` object and an `args` array to the `WASI` constructor

**Comment by Gregoirevda** [comment]
Thanks!
I'm getting other issues now:
https://github.com/CraneStation/wasmtime/issues/161
